### ISSUE TITLE
Grafiken und UI

### ISSUE THREAD

**Issue by GeorgS** [INSY5BI/INSY5BI.github.io#6]
- [x] Grafiken für Meteoriten Spaceship suchen und anpassen
- [x] UI überlegen und gestalten

**Comment by TimTeufl** [comment]
![spaceship](https://cloud.githubusercontent.com/assets/10740254/6145900/05af130e-b1e7-11e4-88db-c2591a99c6d5.png)
Spaceship

**Comment by TimTeufl** [comment]
![meteor](https://cloud.githubusercontent.com/assets/10740254/6145944/950d5f38-b1e7-11e4-913e-72efd61b77b4.png)
Meteorit

**Comment by TimTeufl** [comment]
Schrift einbetten http://createjs.com/tutorials/Fonts/

**Comment by TimTeufl** [comment]
als Schriftart würde ich: http://www.dafont.com/de/caviar-dreams.font vorschlagen
